### ISSUE TITLE
Query regarding Mixture-of-Experts

### ISSUE THREAD

**Issue by Mat8e** [iffsid/mmvae#9]
Hello, thanks for sharing the code.

This is not an issue, but rather a question of where the Mixture-of-Experts operation is involved in the mmvae.py code. I thought it would be used in ```forward()``` but I cannot somehow clearly identify it in these lines: 
```
    def forward(self, x, K=1):
        qz_xs, zss = [], []
        # initialise cross-modal matrix
        px_zs = [[None for _ in range(len(self.vaes))] for _ in range(len(self.vaes))]
        for m, vae in enumerate(self.vaes):
            qz_x, px_z, zs = vae(x[m], K=K)
            qz_xs.append(qz_x)
            zss.append(zs)
            px_zs[m][m] = px_z  # fill-in diagonal
        for e, zs in enumerate(zss):
            for d, vae in enumerate(self.vaes):
                if e != d:  # fill-in off-diagonal
                    px_zs[e][d] = vae.px_z(*vae.dec(zs))
        return qz_xs, px_zs, zss
```

It seems like ```qz_xs``` don't mix and ```px_zs``` are only computed with the posterior distributions of single modalities. Don't you need to use mixture of experts to combine here the  posterior distributions ```qz_xs``` ?

Thanks,

**Comment by iffsid** [comment]
Taking expectations over mixture distributions allows factoring out the expectation as a sum.
This might help.

![](https://quicklatex.com/cache3/22/ql_073ceb3ab6f2213558e676397d22da22_l3.png)

Note that all the `forward` function does is accumulate the required values for this computation---notice that the likelihoods are a 'matrix' because of the nested summation involved (last line).
The actual objective itself is computed, using these accumulated values, in `objectives.py`.

**Comment by Mat8e** [comment]
Thank you for the explanation, everything is clear now.
